export const MAGE_DECK = [
  {
    artist: "Arthur Bozonnet",
    attack: 3,
    cardClass: "MAGE",
    collectible: true,
    cost: 2,
    dbfId: 69696,
    flavor: "And he can't get up.",
    health: 2,
    howToEarn: "Unlocked at level 7.",
    howToEarnGolden: "Unlocked after winning 100 games as Mage.",
    id: "CORE_AT_003",
    mechanics: ["HEROPOWER_DAMAGE"],
    name: "Fallen Hero",
    rarity: "RARE",
    set: "CORE",
    text: "Your Hero Power deals 1 extra damage.",
    type: "MINION",
  },
  {
    artist: "Christopher Moeller",
    attack: 6,
    cardClass: "MAGE",
    collectible: true,
    cost: 6,
    dbfId: 69697,
    flavor:
      'The Grand Tournament has a "No dragons allowed" policy, but it\'s rarely enforced.',
    health: 7,
    howToEarn: "Unlocked at level 9.",
    howToEarnGolden: "Unlocked after winning 250 games as Mage.",
    id: "CORE_AT_008",
    name: "Coldarra Drake",
    race: "DRAGON",
    rarity: "EPIC",
    set: "CORE",
    text: "You can use your Hero Power any number of times.",
    type: "MINION",
  },
  {
    artist: "Konstantin Turovec",
    cardClass: "MAGE",
    collectible: true,
    cost: 1,
    dbfId: 69698,
    flavor: "Literally starstruck.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_BOT_453",
    name: "Shooting Star",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "ARCANE",
    text: "Deal $1 damage to a minion and the minions next to it.",
    type: "SPELL",
  },
  {
    artist: "Dave Berggren",
    cardClass: "MAGE",
    collectible: true,
    cost: 3,
    dbfId: 69500,
    flavor:
      "Playing this card makes you SMARTER.  And let's face it: we could all stand to be a little smarter.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_CS2_023",
    name: "Arcane Intellect",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "ARCANE",
    text: "Draw 2 cards.",
    type: "SPELL",
  },
  {
    artist: "Ralph Horsley",
    cardClass: "MAGE",
    collectible: true,
    cost: 4,
    dbfId: 69501,
    flavor:
      "This spell is useful for burning things.  If you're looking for spells that toast things, or just warm them a little, you're in the wrong place.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_CS2_029",
    name: "Fireball",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "FIRE",
    text: "Deal $6 damage.",
    type: "SPELL",
  },
  {
    artist: "Romain De Santi",
    cardClass: "MAGE",
    collectible: true,
    cost: 7,
    dbfId: 69502,
    flavor:
      "When the ground is on fire, you should <i>not</i> stop, drop, and roll.",
    howToEarn: "Unlocked at level 8.",
    howToEarnGolden: "Unlocked after winning 250 games as Mage.",
    id: "CORE_CS2_032",
    name: "Flamestrike",
    rarity: "EPIC",
    set: "CORE",
    spellSchool: "FIRE",
    text: "Deal $5 damage to all enemy minions.",
    type: "SPELL",
  },
  {
    artist: "John Avon",
    attack: 3,
    cardClass: "MAGE",
    collectible: true,
    cost: 4,
    dbfId: 69503,
    flavor:
      "Don't summon a water elemental at a party.  It'll dampen the mood.",
    health: 6,
    howToEarn: "Unlocked at level 4.",
    howToEarnGolden: "Unlocked after winning 100 games as Mage.",
    id: "CORE_CS2_033",
    mechanics: ["FREEZE"],
    name: "Water Elemental",
    race: "ELEMENTAL",
    rarity: "RARE",
    set: "CORE",
    text: "<b>Freeze</b> any character damaged by this minion.",
    type: "MINION",
  },
  {
    artist: "Leo Che",
    cardClass: "MAGE",
    collectible: true,
    cost: 3,
    dbfId: 69606,
    flavor:
      "Magi of the Kirin Tor were casting Cubes of Cold for many years before Cones came into fashion some 90 years ago.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_EX1_275",
    mechanics: ["FREEZE"],
    name: "Cone of Cold",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "FROST",
    text: "<b>Freeze</b> a minion and the minions next to it, and deal $1 damage to them.",
    type: "SPELL",
  },
  {
    artist: "Jason Chan",
    cardClass: "MAGE",
    collectible: true,
    cost: 3,
    dbfId: 69607,
    flavor:
      "What's the difference between a mage playing with Counterspell and a mage who isn't?  The mage who isn't is getting Pyroblasted in the face.",
    howToEarn: "Unlocked at level 6.",
    howToEarnGolden: "Unlocked after winning 100 games as Mage.",
    id: "CORE_EX1_287",
    mechanics: ["SECRET"],
    name: "Counterspell",
    rarity: "RARE",
    referencedTags: ["COUNTER"],
    set: "CORE",
    spellSchool: "ARCANE",
    text: "<b>Secret:</b> When your opponent casts a spell, <b>Counter</b> it.",
    type: "SPELL",
  },
  {
    artist: "Alex Garner",
    cardClass: "MAGE",
    collectible: true,
    cost: 3,
    dbfId: 69608,
    flavor: "This is Rank 1.  Rank 2 is Chocolate Milk Barrier.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_EX1_289",
    mechanics: ["SECRET"],
    name: "Ice Barrier",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "FROST",
    text: "<b>Secret:</b> When your\nhero is attacked,\ngain 8 Armor.",
    type: "SPELL",
  },
  {
    artist: "Raven Mimura",
    cardClass: "MAGE",
    collectible: true,
    cost: 3,
    dbfId: 69609,
    flavor: '"You go first." - Krush\'gor the Behemoth, to his pet boar.',
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_EX1_294",
    mechanics: ["SECRET"],
    name: "Mirror Entity",
    rarity: "COMMON",
    set: "CORE",
    spellSchool: "ARCANE",
    text: "<b>Secret:</b> After your opponent plays a minion, summon a copy of it.",
    type: "SPELL",
  },
  {
    artist: "Gonzalo Ordonez",
    cardClass: "MAGE",
    collectible: true,
    cost: 1,
    dbfId: 69699,
    flavor: "Lick the ice block. I triple-double-dog-dare-you.",
    howToEarn: "Unlocked at level 2.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_GIL_801",
    name: "Snap Freeze",
    rarity: "COMMON",
    referencedTags: ["FREEZE"],
    set: "CORE",
    spellSchool: "FROST",
    text: "<b>Freeze</b> a minion.\nIf it's already <b>Frozen</b>, destroy it.",
    type: "SPELL",
  },
  {
    artist: "A. J. Nazzaro",
    attack: 1,
    cardClass: "MAGE",
    collectible: true,
    cost: 1,
    dbfId: 69700,
    flavor:
      "His idol is the Green Hills of Stranglethorn, and he won't shut up about it.",
    health: 1,
    howToEarn: "Unlocked at level 5.",
    howToEarnGolden: "Unlocked after winning 100 games as Mage.",
    id: "CORE_KAR_009",
    mechanics: ["BATTLECRY"],
    name: "Babbling Book",
    rarity: "RARE",
    set: "CORE",
    text: "<b>Battlecry:</b> Add a random Mage spell to your hand.",
    type: "MINION",
  },
  {
    artist: "Ben Zhang",
    attack: 6,
    cardClass: "MAGE",
    collectible: true,
    cost: 5,
    dbfId: 69701,
    flavor: "Despite the name, he's a solid conjurer.",
    health: 4,
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_LOE_003",
    mechanics: ["BATTLECRY", "DISCOVER"],
    name: "Ethereal Conjurer",
    rarity: "COMMON",
    set: "CORE",
    text: "<b>Battlecry: Discover</b> a spell.",
    type: "MINION",
  },
  {
    artist: "Eva Widermann",
    attack: 2,
    cardClass: "MAGE",
    collectible: true,
    cost: 2,
    dbfId: 69702,
    flavor: "What did you draw? Shhhh… it’s a secret.",
    health: 3,
    howToEarn: "Unlocked at level 3.",
    howToEarnGolden: "Unlocked after winning 50 games as Mage.",
    id: "CORE_UNG_020",
    mechanics: ["BATTLECRY"],
    name: "Arcanologist",
    rarity: "COMMON",
    referencedTags: ["SECRET"],
    set: "CORE",
    text: "<b>Battlecry:</b> Draw a <b>Secret</b>.",
    type: "MINION",
  },
  {
    artist: "Luke Mancini",
    attack: 5,
    cardClass: "MAGE",
    collectible: true,
    cost: 5,
    dbfId: 62347,
    elite: true,
    flavor: "With Medivh as her son, nothing YOU do could ever disappoint her.",
    health: 5,
    howToEarn: "Unlocked at level 10.",
    howToEarnGolden: "Unlocked after winning 500 games as Mage.",
    id: "CS3_001",
    mechanics: ["DEATHRATTLE", "SPELLPOWER"],
    name: "Aegwynn, the Guardian",
    rarity: "LEGENDARY",
    set: "CORE",
    spellDamage: 2,
    text: "<b>Spell Damage +2</b>\n<b>Deathrattle:</b> The next minion you draw inherits these powers.",
    type: "MINION",
  },
];

export const WARRIOR_DECK = [
  {
    artist: "Dany Orizio",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 3,
    dbfId: 76304,
    flavor:
      "You might think bashing doesn't take a lot of practice.  It doesn't.",
    howToEarn: "Unlocked at level 7.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_AT_064",
    name: "Bash",
    rarity: "COMMON",
    set: "CORE",
    text: "Deal $3 damage.\nGain 3 Armor.",
    type: "SPELL",
  },
  {
    artist: "Dany Orizio",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 1,
    dbfId: 69535,
    flavor: "It's okay, he deserved it.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_CS2_108",
    name: "Execute",
    rarity: "COMMON",
    set: "CORE",
    text: "Destroy a damaged enemy minion.",
    type: "SPELL",
  },
  {
    artist: "E. M. Gist",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 2,
    dbfId: 69638,
    flavor:
      "\"Dun da dun, dun da dun\": if you've heard an ogre sing this, it's too late.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_EX1_391",
    name: "Slam",
    rarity: "COMMON",
    set: "CORE",
    text: "Deal $2 damage to a minion. If it survives, draw a card.",
    type: "SPELL",
  },
  {
    artist: "Jonboy Meyers",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 1,
    dbfId: 69556,
    flavor:
      'The way to tell seasoned warriors from novice ones: the novices yell "wheeeee" while whirlwinding.',
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_EX1_400",
    name: "Whirlwind",
    rarity: "COMMON",
    set: "CORE",
    text: "Deal $1 damage to ALL minions.",
    type: "SPELL",
  },
  {
    artist: "Greg Hildebrandt",
    attack: 1,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 2,
    dbfId: 69639,
    flavor: "She accepts guild funds for repairs!",
    health: 4,
    howToEarn: "Unlocked at level 3.",
    howToEarnGolden: "Unlocked after winning 100 games as Warrior.",
    id: "CORE_EX1_402",
    mechanics: ["TRIGGER_VISUAL"],
    name: "Armorsmith",
    rarity: "RARE",
    set: "CORE",
    text: "Whenever a friendly minion takes damage, gain 1 Armor.",
    type: "MINION",
  },
  {
    artist: "Wayne Reynolds",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 5,
    dbfId: 69640,
    flavor: "Do you know the first rule of Brawl Club?",
    howToEarn: "Unlocked at level 5.",
    howToEarnGolden: "Unlocked after winning 250 games as Warrior.",
    id: "CORE_EX1_407",
    name: "Brawl",
    rarity: "EPIC",
    set: "CORE",
    text: "Destroy all minions except one. <i>(chosen randomly)</i>",
    type: "SPELL",
  },
  {
    artist: "Raymond Swanland",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 1,
    dbfId: 69641,
    flavor:
      '"What is a better weapon? The sharp one your enemies expect, or the blunt one they ignore?" - The Art of Warrior, Chapter 9',
    howToEarn: "Unlocked at level 8.",
    howToEarnGolden: "Unlocked after winning 250 games as Warrior.",
    id: "CORE_EX1_410",
    mechanics: ["AFFECTED_BY_SPELL_POWER"],
    name: "Shield Slam",
    rarity: "EPIC",
    set: "CORE",
    text: "Deal 1 damage to a minion for each Armor you have.",
    type: "SPELL",
  },
  {
    artist: "Glenn Rane",
    attack: 4,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 8,
    dbfId: 69643,
    elite: true,
    flavor:
      "Grommash drank the tainted blood of Mannoroth, dooming the orcs to green skin and red eyes!  Maybe not his best decision.",
    health: 9,
    howToEarn: "Unlocked at level 10.",
    howToEarnGolden: "Unlocked after winning 500 games as Warrior.",
    id: "CORE_EX1_414",
    mechanics: ["CHARGE", "ENRAGED"],
    name: "Grommash Hellscream",
    rarity: "LEGENDARY",
    set: "CORE",
    text: "<b>Charge</b>\nHas +6 Attack while damaged.",
    type: "MINION",
  },
  {
    artist: "Phroilan Gardner",
    attack: 2,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 2,
    dbfId: 69644,
    flavor: '"I\'m going to need you to come in on Sunday." - Cruel Taskmaster',
    health: 2,
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_EX1_603",
    mechanics: ["BATTLECRY"],
    name: "Cruel Taskmaster",
    rarity: "COMMON",
    set: "CORE",
    targetingArrowText: "Deal 1 damage and grant +2 Attack.",
    text: "<b>Battlecry:</b> Deal 1 damage to a minion and give it +2 Attack.",
    type: "MINION",
  },
  {
    artist: "Simon Bisley",
    attack: 2,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 3,
    dbfId: 69645,
    flavor:
      "He used to work as an accountant before he tried his hand at Berserkering.",
    health: 4,
    howToEarn: "Unlocked at level 4.",
    howToEarnGolden: "Unlocked after winning 100 games as Warrior.",
    id: "CORE_EX1_604",
    mechanics: ["TRIGGER_VISUAL"],
    name: "Frothing Berserker",
    rarity: "RARE",
    set: "CORE",
    text: "Whenever a minion takes damage, gain +1 Attack.",
    type: "MINION",
  },
  {
    artist: "Michael Komarck",
    cardClass: "WARRIOR",
    collectible: true,
    cost: 3,
    dbfId: 76302,
    flavor: "Shields were invented because Face Block is USELESS.",
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_EX1_606",
    name: "Shield Block",
    rarity: "COMMON",
    set: "CORE",
    text: "Gain 5 Armor.\nDraw a card.",
    type: "SPELL",
  },
  {
    artist: "Arthur Bozonnet",
    attack: 4,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 5,
    dbfId: 76301,
    elite: true,
    flavor:
      "You either die a villain, or live long enough to see yourself become the hero.",
    health: 5,
    howToEarn: "Unlocked at level 10.",
    howToEarnGolden: "Unlocked after winning 500 games as Warrior.",
    id: "CORE_GIL_547",
    mechanics: ["RUSH", "TRIGGER_VISUAL"],
    name: "Darius Crowley",
    rarity: "LEGENDARY",
    set: "CORE",
    text: "[x]<b>Rush</b>\nAfter this attacks and kills\na minion, gain +2/+2.",
    type: "MINION",
  },
  {
    artist: "Alex Horley Orlandelli",
    attack: 5,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 5,
    dbfId: 69741,
    flavor:
      "She has three shieldbearers in her party to supply her with back ups when she gets low on durability.",
    health: 5,
    howToEarn: "Unlocked at level 6.",
    howToEarnGolden: "Unlocked after winning 100 games as Warrior.",
    id: "CORE_GVG_053",
    mechanics: ["BATTLECRY"],
    name: "Shieldmaiden",
    rarity: "RARE",
    set: "CORE",
    text: "<b>Battlecry:</b> Gain 5 Armor.",
    type: "MINION",
  },
  {
    artist: "Paul Mafayon",
    attack: 2,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 4,
    dbfId: 76303,
    flavor:
      'He thought the set was called "Flippers of the Old Cods" and hungrily volunteered to be in it.  He is definitely going to get his hearing checked.',
    health: 6,
    howToEarn: "Unlocked at level 2.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CORE_OG_218",
    mechanics: ["ENRAGED", "TAUNT"],
    name: "Bloodhoof Brave",
    rarity: "COMMON",
    set: "CORE",
    text: "<b>Taunt</b>\nHas +3 Attack while damaged.",
    type: "MINION",
  },
  {
    artist: "Vika Yarova",
    attack: 2,
    cardClass: "WARRIOR",
    collectible: true,
    cost: 1,
    dbfId: 62462,
    flavor: "Piracy is technically a discount.",
    health: 1,
    howToEarn: "Unlocked at level 1.",
    howToEarnGolden: "Unlocked after winning 50 games as Warrior.",
    id: "CS3_008",
    mechanics: ["BATTLECRY"],
    name: "Bloodsail Deckhand",
    race: "PIRATE",
    rarity: "COMMON",
    set: "CORE",
    text: "[x]<b>Battlecry:</b> The next\nweapon you play costs\n(1) less.",
    type: "MINION",
  },
];
